language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/Gemfile.activesupport-4.0.x
  - test/gemfiles/Gemfile.activesupport-4.0.x
sudo: false
